### PR TITLE
pip install

### PR DESCRIPTION
**Pull request by hev**
Added pip install back to example READMEs and updated venv link to somewhere public.

### CODE REVIEW

**Comment by randersenYB** [comment]
For "Quote Search" the step to install waitress-serve is missing. Can be installed with:
`sudo apt install python3-waitress`

**Comment by randersenYB** [comment]
In the prism-image-search readme file:

-  section named “Performing a quote search”, shouldn’t that be a different section name to reflect image search?
- the symbolic link to the "./static/images/data" folder was committed to the repro pointing to an invalid folder (looks like Adam's home folder). Had to unlink data...
- the second step (i.e., ln -s ~/Pictures prism/static/images/data), I would suggest, be moved after "Pip Install Dependencies" and the command be:
`ln -s <Folder of Your Pictures> ./static/images/data`
- the step to install waitress-serve is missing. Can be installed with:
`sudo apt install python3-waitress`
- Once running, it would be nice if there is a tutorial how its' works. I don't know what to enter in the web browser. 

Once I was able to run, I received the following exception:
```
waitress-serve --host 127.0.0.1 --port 8080 --th
reads 32 prism:app
/home/randersen/.local/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
INFO:indexer:Creating index
INFO:indexer:Index already exists
INFO:waitress:Serving on http://127.0.0.1:8080
Checking for new files: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 775.57it/s]
INFO:indexer:Found new files to index
Indexing new files:   0%|                                                                         | 0/1 [00:00<?, ?it/s]Unused or unrecognized kwargs: padding.
Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
Aborted
```
BTW, I think we seen this before and all my images are new Ubuntu-22.04 instances (everything get loaded freshly)

**Comment by jdogmcsteezy** [comment]
> For "Quote Search" the step to install waitress-serve is missing. Can be installed with: `sudo apt install python3-waitress`

@randersenYB, I am just now reading these. Do you need to install python3-waitress even after installing the virtual environment? On my fresh installs, I have not needed to explicitly install `python3-waitress`

**Comment by jdogmcsteezy** [comment]
@randersenYB This is the dockerfile I use which does not include `python3-waitress`

```
# Prism Dockfile
FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && pip3 install setuptools sql

RUN mkdir /prism
COPY ./prism /prism
WORKDIR /prism
RUN python3 -m pip install -r requirements.txt

ENTRYPOINT ["waitress-serve"]
CMD ["--host=0.0.0.0", "--port=8080", "--threads=32", "prism:app"]
```

**Comment by hev** [comment]
I am going to close this. Probably should still fix some things I started on here but I need to revisit.

**Pull request closed without merging**
